services:
  db-social-network:
    container_name: db-social-network
    image: postgres:16.3-alpine
    restart: always
    command: postgres -c 'max_connections=100' && chmod +x /docker-entrypoint-initdb.d/init-database.sh
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      SOCIAL_NETWORK_SCHEMA: social_network
      SOCIAL_NETWORK_USER: social_network
      SOCIAL_NETWORK_PASSWORD: social_network
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5433:5432"
    networks:
      - intranet
  redis-social-network:
    image: redis:alpine3.20
    container_name: redis-social-network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  postgres:
  redis-data:
networks:
  intranet:
    driver: bridge